var homeDefine = {
  INSERT_TOPIC_RESPONSE: "INSERT_TOPIC_RESPONSE",
  LIKE_TOPIC_RESPONSE: "LIKE_TOPIC_RESPONSE",
  DISLIKE_TOPIC_RESPONSE: "DISLIKE_TOPIC_RESPONSE",
  GET_TOPIC_RESPONSES: "GET_TOPIC_RESPONSES",
  GET_RANDOM_TOPIC: "GET_RANDOM_TOPIC",
  GET_TOPIC: "GET_TOPIC",
  GET_SEARCH_RESULTS: "GET_SEARCH_RESULTS"
};
